In [2]:
import numpy as np 
np.random.seed(93)

In [40]:
""" Multiplication of matrix 
    use @ operator or np.matmul
    not * (*: will do multiplication element * element !!)

    cf: https://numpy.org/doc/2.2/reference/generated/numpy.matmul.html
    conditions must be filled: (n,k),(k,m)->(n,m)
"""
matA = np.random.randint(0, 100, size=6)
matA = matA.reshape((3, 2))
matA

array([[72, 87],
       [28, 47],
       [15,  5]])

In [44]:
matB = np.random.randint(0, 50, size=6)
matB = matB.reshape((2, 3))
matB

array([[ 1, 41, 41],
       [10, 39, 41]])

In [47]:
matC = matA @ matB
matC

array([[ 942, 6345, 6519],
       [ 498, 2981, 3075],
       [  65,  810,  820]])

In [48]:
matD = matB @ matA
matD

array([[1835, 2219],
       [2427, 2908]])

In [49]:
""" Transpose of matrix 
    - getting as attribute of ndarray object
    - by calling np.transpose (cf: https://numpy.org/doc/2.1/reference/generated/numpy.matrix.transpose.html)
"""
matA.T # getting as attribute of ndarray

array([[72, 28, 15],
       [87, 47,  5]])

In [51]:
matE = np.transpose(matA) # by calling nb.transpose of NumPy
matE

array([[72, 28, 15],
       [87, 47,  5]])

In [4]:
arrA = np.array([1, np.nan, 3])

In [6]:
# Invalid result when encouter NaN values
print(np.std(arrA))
print(np.mean(arrA))
print(np.var(arrA))

nan
nan
nan


In [9]:
# To ignore NaN values we have to use adapted functions
# Such: https://numpy.org/doc/stable/reference/generated/numpy.nanstd.html
print(np.nanstd(arrA))
print(np.nanmean(arrA))
print(np.nanvar(arrA))

1.0
2.0
1.0


In [12]:
sample_data = np.array([
    [12.4, 15.2, np.nan],
    [18.1, np.nan, 20.5]
])

nan_mask = np.isnan(sample_data)

In [14]:
sample_data[nan_mask] = 10
sample_data

array([[12.4, 15.2, 10. ],
       [18.1, 10. , 20.5]])